blank_issues_enabled: yes
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Musholic/rusty-last-epoch-planner/discussions
    about: Please ask questions unrelated to actual bugs/issues here.
